/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    'fleet-owners': FleetOwner;
    drivers: Driver;
    vehicles: Vehicle;
    media: Media;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  role: 'admin' | 'customer' | 'fleet_owner' | 'driver';
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fleet-owners".
 */
export interface FleetOwner {
  id: string;
  user: string | User;
  companyName: string;
  businessRegistrationNumber: string;
  address: {
    street: string;
    city: string;
    state: string;
    zip: string;
  };
  documents: {
    businessLicense: string | Media;
    insuranceCertificate: string | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "drivers".
 */
export interface Driver {
  id: string;
  user: string | User;
  fleetOwner: string | FleetOwner;
  licenseNumber: string;
  licenseExpiry: string;
  experience: number;
  documents: {
    driverLicense: string | Media;
    medicalCertificate: string | Media;
  };
  status: 'AVAILABLE' | 'ON_TRIP' | 'OFF_DUTY';
  assignedVehicle?: (string | null) | Vehicle;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicles".
 */
export interface Vehicle {
  id: string;
  fleetOwner: string | FleetOwner;
  type: 'TRUCK' | 'VAN' | 'TRAILER';
  make: string;
  model: string;
  year: number;
  licensePlate: string;
  capacity: {
    weight: number;
    volume: number;
  };
  documents: {
    registration: string | Media;
    insurance: string | Media;
    inspection: string | Media;
  };
  status: 'AVAILABLE' | 'IN_USE' | 'MAINTENANCE';
  maintenanceHistory?:
    | {
        date: string;
        description: string;
        cost: number;
        id?: string | null;
      }[]
    | null;
  assignedDriver?: (string | null) | Driver;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}